version: "3.8"

services:
  # MySQL
  db:
    container_name: "db"
    # path配下のDockerfile読み込み
    build: 
      context: ./docker/mysql
      dockerfile: ./debug.Dockerfile    
    # コンテナが落ちたら再起動する
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: worder
      MYSQL_USER: user
      MYSQL_PASSWORD: password # ユーザのパスワード
      MYSQL_ROOT_PASSWORD: password # ルートパスワード
    ports:
      - "5432:5432"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d # 定義どおりにテーブル作成
      - ./log/mysql:/var/log/mysql # ログの保存
    networks:
      - local-net

  # FastAPI
  api:
    # db起動後に立ち上げる
    links:
      - db
    container_name: "api"
    # path配下のDockerfile読み込み
    build: 
      context: ./docker/api
      dockerfile: ./debug.Dockerfile
    restart: always
    volumes:
      - ./app:/worder/app
    expose:
      - "8080"
      - "5678"
    ports:
      - "8080:8080"
      - "5678:5678"
    networks:
      - local-net

# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  local-net:
    driver: bridge
